apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: syntribos-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-syntribos-cronjob
            image: tonytan4ever/docker-openstack-syntribos-customized:latest
            env:
              - name: config_file_location
                value: /root/.syntribos/syntribos.conf
          restartPolicy: OnFailure
